[package]
name = "high-level-command-language"
version = "0.1.0"
authors = ["JozsefA <jozsefaug@gmail.com>"]
edition = "2018"
build = "build.rs"

[profile.release]
lto = true

[build-dependencies]
lalrpop = { version = "0.19.0" }

[dependencies]
lalrpop-util = "0.19.0"
regex = "1.3.9"
phf = { version = "0.8.0", features = ["macros"] }
lasso = { version = "0.2.2", features = [] }
fxhash = "0.2.1"
threadpool = "1.8.1"