[package]
name = "high-level-command-language"
version = "0.1.0"
authors = ["JozsefA <jozsefaug@gmail.com>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
lalrpop = { version = "0.19.0" }

[dependencies]
lalrpop-util = "0.19.0"
regex = "1.3.9"
phf = { version = "0.8.0", features = ["macros"] }
string-interner = "0.7.1"