[package]
name = "hlcl_span"
version = "0.1.0"
authors = ["JozsefA <jozsefaug@gmail.com>"]
edition = "2018"

[lib]
name = "hlcl_span"
path = "lib.rs"
doctest = false

[dependencies]
derive_more = "0.99.9"